<template>
  <section class="mx-auto max-w-xl space-y-4 px-1 sm:px-0"><p v-if="query.isLoading.value" class="rounded-xl border p-4 text-sm text-muted-foreground">Đang tải lệnh...</p><template v-else-if="order"><header class="rounded-xl bg-primary p-5 text-primary-foreground"><p class="text-sm opacity-80">{{ order.order_no }}</p><h1 class="mt-1 text-xl font-semibold">{{ formatDispatchDate(order.scheduled_start_at) }}</h1><p class="mt-2 text-sm">{{ scheduleStatusLabel(order.status) }}</p></header><section class="rounded-xl border bg-card p-5"><p class="font-semibold">{{ order.customer_name || 'Khách hàng' }}</p><a v-if="order.customer_phone" class="mt-1 inline-block text-sm text-primary underline" :href="`tel:${order.customer_phone}`">{{ order.customer_phone }}</a><dl class="mt-4 space-y-3 text-sm"><div><span class="text-muted-foreground">Đón</span><p>{{ order.pickup_location || '—' }}</p></div><div><span class="text-muted-foreground">Trả</span><p>{{ order.dropoff_location || '—' }}</p></div><div><span class="text-muted-foreground">Xe</span><p>{{ order.assignment?.license_plate || '—' }}</p></div></dl></section><form v-if="order.status === 'ASSIGNED'" class="space-y-3 rounded-xl border bg-card p-5" @submit.prevent="start"><h2 class="font-semibold">Bắt đầu chuyến</h2><label class="grid gap-1 text-sm">Thời gian<Input v-model="startForm.actual_start_at" type="datetime-local" required /></label><label class="grid gap-1 text-sm">ODO đầu<Input v-model.number="startForm.start_odometer" type="number" min="0" required /></label><Button class="h-12 w-full text-base" type="submit" :disabled="mutations.startOrder.isPending.value">Bắt đầu</Button></form><form v-else-if="order.status === 'IN_PROGRESS'" class="space-y-3 rounded-xl border bg-card p-5" @submit.prevent="complete"><h2 class="font-semibold">Hoàn thành chuyến</h2><label class="grid gap-1 text-sm">Thời gian kết thúc<Input v-model="completeForm.actual_end_at" type="datetime-local" required /></label><label class="grid gap-1 text-sm">ODO cuối<Input v-model.number="completeForm.end_odometer" type="number" min="0" required /></label><label class="grid gap-1 text-sm">Quãng đường (km)<Input v-model.number="completeForm.actual_distance_km" type="number" min="0" required /></label><label class="grid gap-1 text-sm">Giờ chờ<Input v-model.number="completeForm.waiting_hours" type="number" min="0" step="0.25" /></label><Button class="h-12 w-full text-base" type="submit" :disabled="mutations.completeOrder.isPending.value">Hoàn thành</Button></form><p v-else class="rounded-xl border p-4 text-sm text-muted-foreground">Không có thao tác nào cho trạng thái hiện tại.</p></template><p v-else class="rounded-xl border border-destructive/30 p-4 text-sm text-destructive">Bạn không thể truy cập lệnh này.</p></section>
</template>
<script setup lang="ts">
import { useDispatchMutations, useMyOrderQuery } from '@/modules/dispatch/dispatch.composables'; import { formatDispatchDate, scheduleStatusLabel } from '@/modules/dispatch/dispatch.format'; import { Button } from '@/shared/components/ui/button'; import { Input } from '@/shared/components/ui/input'; import { computed, reactive } from 'vue'; import { useRoute } from 'vue-router'; import { toast } from 'vue-sonner'
const route = useRoute(); const id = computed(() => Number(route.params.id)); const query = useMyOrderQuery(() => id.value); const order = computed(() => query.data.value); const mutations = useDispatchMutations(); const startForm = reactive({ actual_start_at: '', start_odometer: 0 }); const completeForm = reactive({ actual_end_at: '', end_odometer: 0, actual_distance_km: 0, waiting_hours: undefined as number | undefined })
async function run(action: () => Promise<unknown>, message: string) { try { await action(); await query.refetch(); toast.success(message) } catch (error) { await query.refetch(); toast.error(error instanceof Error ? error.message : 'Không thể cập nhật. Trạng thái đã được làm mới.') } }
function start() { return run(() => mutations.startOrder.mutateAsync({ id: id.value, data: { actual_start_at: new Date(startForm.actual_start_at).toISOString(), start_odometer: startForm.start_odometer } }), 'Đã bắt đầu chuyến.') }
function complete() { return run(() => mutations.completeOrder.mutateAsync({ id: id.value, data: { actual_end_at: new Date(completeForm.actual_end_at).toISOString(), end_odometer: completeForm.end_odometer, actual_distance_km: completeForm.actual_distance_km, waiting_hours: completeForm.waiting_hours } }), 'Đã hoàn thành chuyến.') }
</script>
