<script setup lang="ts">
import { ref, watch } from 'vue'
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import { useRoute } from 'vue-router'
import { RoleService } from '@/services/role.service'; import { PermissionService } from '@/services/permission.service'; import { Button } from '@/shared/components/ui/button'; import { toast } from 'vue-sonner'
const route = useRoute(); const id = Number(route.params.id); const client = useQueryClient(); const roleQuery = useQuery({ queryKey: ['roles', id], queryFn: () => RoleService.getRole(id) }); const permissionsQuery = useQuery({ queryKey: ['permissions'], queryFn: PermissionService.getPermissions }); const ids = ref<number[]>([])
watch([() => roleQuery.data.value, () => permissionsQuery.data.value], ([role, permissions]) => { if (role && permissions) ids.value = permissions.filter(p => role.permissions.includes(p.name)).map(p => p.id) }, { immediate: true })
const save = useMutation({ mutationFn: () => RoleService.syncPermissions(id, ids.value), onSuccess: async () => { toast.success('Đã cập nhật quyền của vai trò.'); await client.invalidateQueries({ queryKey: ['roles'] }) } })
function toggle(value: number) { const i = ids.value.indexOf(value); i < 0 ? ids.value.push(value) : ids.value.splice(i, 1) }
</script>
<template><section v-if="roleQuery.data.value" class="space-y-5"><header><h1 class="text-2xl font-semibold">{{ roleQuery.data.value.name }}</h1><p class="text-sm text-muted-foreground">{{ roleQuery.data.value.is_system ? 'Vai trò hệ thống' : 'Vai trò tùy chỉnh' }}</p></header><section class="rounded-xl border bg-card"><header class="border-b px-4 py-3"><h2 class="font-semibold">Quyền của vai trò</h2></header><div class="max-h-[55svh] overflow-auto p-3"><label v-for="permission in permissionsQuery.data.value?.filter((p) => p.is_active)" :key="permission.id" class="flex items-center gap-2 border-b py-2 text-sm"><input type="checkbox" :checked="ids.includes(permission.id)" :disabled="roleQuery.data.value.is_system" @change="toggle(permission.id)">{{ permission.name }}</label></div><footer class="border-t p-3 text-right"><Button size="sm" :disabled="roleQuery.data.value.is_system || save.isPending.value" @click="save.mutate()">Lưu thay đổi</Button></footer></section></section></template>
